name = "Trickling_up"
uuid = "3b2b44eb-a8fd-448d-9e15-30ebef6f5bea"
authors = ["Martin Bernstein <martinmbernstein@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
